---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php71-php
    - php71-php-fpm
    - php71-php-common
    - php71-php-cli
    - php71-php-devel
    - php71-php-gd
    - php71-php-curl
    - php71-php-json
    - php71-php-opcache
    - php71-php-xml
    - php71-php-mbstring
    - php71-php-pdo
    - php71-php-mysql

- name: Create php-fpm run directory
  file:
    path: /var/run/php-fpm
    state: directory

- name: Disable default pool
  command: mv /etc/opt/remi/php71/php-fpm.d/www.conf /etc/opt/remi/php71/php-fpm.d/www.disabled creates=/etc/opt/remi/php71/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/opt/remi/php71/php-fpm.d/
  notify: restart php-fpm

- name: Increase upload_max_size
  lineinfile:
    path: /etc/opt/remi/php71/php.ini
    regexp: '^upload_max_filesize ='
    line: 'upload_max_filesize = {{ php_upload_max_filesize }}'
  notify: restart php-fpm

- name: Increase post_max_size
  lineinfile:
    path: /etc/opt/remi/php71/php.ini
    regexp: '^post_max_size ='
    line: 'post_max_size = {{ php_post_max_size }}'
  notify: restart php-fpm